/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - name
 *         - lastName
 *         - email
 *         - password
 *         - location
 *       properties:
 *         id:
 *           type: string
 *           description: The autogenerated id of user collection
 *         name:
 *           type: string
 *           description: User name
 *         lastName:
 *           type: string
 *           description: User Last Name
 *         email:
 *           type: string
 *           description: User email address
 *         password:
 *           type: string
 *           description: User password must contain at least a capital letter, numeric and an alphanumeric character.and it should be greater than 6 characters
 *         location:
 *           type: string
 *           description: User location, city or country
 *       example:
 *         id: ka6838t28yhdhbic
 *         name: Jane
 *         lastName: Doe
 *         email: janedoe@email.com
 *         password: !Testing542$
 *         location: Lagos, Nigeria
 */

/**
 * @swagger
 * tags:
 *  name: Auth
 *  description: authetication apis
 */

/**
 * @swagger
 * /register:
 *  post:
 *    summary: register new user
 *    tags: [Auth]
 *    requestBody:
 *    content:
 *      application/json:
 *        schema:
 *          $ref: "#/components/schemas/User"
 *    responses:
 *      200:
 *        description: user created successfully
 *        content:
 *          application/json:
 *            schema:
 *              $ref: "#/components/schemas/User"
 *      500:
 *        description: internal server error
 */
